<?php

define('HTTP_SUCCESS', 200);
define('HTTP_CREATED', 201);
define('HTTP_MOVED', 301);
define('HTTP_MOVED_TEMPORARY', 302);
define('HTTP_VALIDATION_FAILED', 400);
define('HTTP_AUTHENTICATION_FAILED', 401);
define('HTTP_PAYMENT_REQUIRED', 402); 
define('HTTP_FORBIDDEN', 403);
define('HTTP_NOT_FOUND', 404);
define('HTTP_PRECONDITION_FAILED', 412);
define('HTTP_UNPROCESSABLE_ENTITY', 422);
define('HTTP_FAILED_DEPENDENCY', 424); 
define('HTTP_SERVER_ERROR', 500);
